export const GET_CITY_WEATHER_STARTED = 'GET_CITY_WEATHER_STARTED';
export const GET_CITY_WEATHER_SUCCESS = 'GET_CITY_WEATHER_SUCCESS';
export const GET_CITY_WEATHER_FAILURE = 'GET_CITY_WEATHER_FAILURE';
